In [3]:
import numpy as np

In [4]:
range(5)#返回的是0到4的5个数构成的list

range(0, 5)

In [5]:
#arange返回的是一个arange对象不过元素都是一样的
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
range(1,5)

range(1, 5)

In [7]:
np.arange(1,5)#第一个参数是起始点，第二个参数是终止点

array([1, 2, 3, 4])

In [8]:
np.arange(1,10,2)#第三个参数指定的是步长

array([1, 3, 5, 7, 9])