In [16]:
import numpy as np
import array

In [9]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

In [11]:
L2 = [str(c)for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
type(L2[0])

str

In [13]:
L3 = [True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [18]:
L = list(range(10))
A = array.array("i",L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [20]:
np.array([3.14,1,3,5])

array([3.14, 1.  , 3.  , 5.  ])

In [21]:
np.array([1,5,3,4,6],dtype="float32")

array([1., 5., 3., 4., 6.], dtype=float32)

In [22]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [23]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [27]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.random.random((3,3))

array([[0.20464866, 0.09284451, 0.32279736],
       [0.2377975 , 0.54969527, 0.76573881],
       [0.45425852, 0.24443667, 0.04978824]])

In [34]:
np.random.normal(0,1,(3,3))#均值为0，方差为1

array([[-0.69064939,  1.89606652, -1.10222374],
       [ 0.96997839, -0.05266464, -1.26719461],
       [ 0.47164445,  0.12492753,  1.12735665]])

In [35]:
np.random.randint(0,10,(3,3))

array([[1, 9, 5],
       [3, 9, 2],
       [5, 5, 7]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.empty(3)

array([1., 1., 1.])

In [43]:
l = np.zeros(10,dtype ="int16")
l

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [44]:
np.zeros(10,dtype =np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [65]:
x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (3,4))
x3 = np.random.randint(10,size = (3,4,5))


In [55]:
print("x3 size:",x3.size)
print("x3 shape:",x3.shape)
print("x3 ndim:",x3.ndim)

x3 size: 60
x3 shape: (3, 4, 5)
x3 ndim: 3


In [56]:
print("x3 dtype:",x3.dtype)

x3 dtype: int32


In [57]:
x3.itemsize

4

In [58]:
x3.nbytes

240

In [66]:
x1

array([8, 0, 6, 7, 5, 1])

In [67]:
x1[0]

8

In [68]:
x1[:5]

array([8, 0, 6, 7, 5])

In [69]:
x2

array([[2, 6, 1, 5],
       [8, 0, 3, 9],
       [6, 3, 0, 2]])

In [74]:
x2[2,0]

6

In [75]:
x2[0,0] = 12

In [76]:
x2

array([[12,  6,  1,  5],
       [ 8,  0,  3,  9],
       [ 6,  3,  0,  2]])

In [77]:
x2[0]

array([12,  6,  1,  5])

In [78]:
x2[0,0] = 3.14

In [79]:
x2

array([[3, 6, 1, 5],
       [8, 0, 3, 9],
       [6, 3, 0, 2]])

In [81]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x[:5]

array([0, 1, 2, 3, 4])

In [83]:
x[5:]

array([5, 6, 7, 8, 9])

In [84]:
x[::2]

array([0, 2, 4, 6, 8])

In [87]:
x[1::2]

array([1, 3, 5, 7, 9])

In [88]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [93]:
x[8::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [94]:
x2

array([[3, 6, 1, 5],
       [8, 0, 3, 9],
       [6, 3, 0, 2]])

In [95]:
x2[:2,:3]

array([[3, 6, 1],
       [8, 0, 3]])

In [96]:
x2[:2,::2]

array([[3, 1],
       [8, 3]])

In [98]:
x2[::-1,::-1]

array([[2, 0, 3, 6],
       [9, 3, 0, 8],
       [5, 1, 6, 3]])

In [100]:
x2[:,0]

array([3, 8, 6])

In [103]:
x2[0]

array([3, 6, 1, 5])

In [104]:
x2[0,:]

array([3, 6, 1, 5])

In [105]:
print(x2)

[[3 6 1 5]
 [8 0 3 9]
 [6 3 0 2]]
